"""Constants for Crawl AI agent."""

# Robot Types
TYPE_FACTORY = 0
TYPE_SCOUT = 1
TYPE_WORKER = 2
TYPE_MINER = 3

# Directions and bitfields
DIR_NORTH = "NORTH"
DIR_EAST = "EAST"
DIR_SOUTH = "SOUTH"
DIR_WEST = "WEST"
DIR_IDLE = "IDLE"

# Wall bits
WALL_N = 1
WALL_E = 2
WALL_S = 4
WALL_W = 8

# Mapping of string direction to bit field
DIR_TO_BIT = {
    DIR_NORTH: WALL_N,
    DIR_EAST: WALL_E,
    DIR_SOUTH: WALL_S,
    DIR_WEST: WALL_W,
}

# Coordinate delta mappings
DIR_TO_DELTA = {
    DIR_NORTH: (0, 1),
    DIR_EAST: (1, 0),
    DIR_SOUTH: (0, -1),
    DIR_WEST: (-1, 0),
    DIR_IDLE: (0, 0),
}

DELTA_TO_DIR = {
    (0, 1): DIR_NORTH,
    (1, 0): DIR_EAST,
    (0, -1): DIR_SOUTH,
    (-1, 0): DIR_WEST,
    (0, 0): DIR_IDLE,
}

# Directions list
ALL_DIRECTIONS = [DIR_NORTH, DIR_EAST, DIR_SOUTH, DIR_WEST]

# Actions
ACT_BUILD_SCOUT = "BUILD_SCOUT"
ACT_BUILD_WORKER = "BUILD_WORKER"
ACT_BUILD_MINER = "BUILD_MINER"

ACT_JUMP_NORTH = "JUMP_NORTH"
ACT_JUMP_EAST = "JUMP_EAST"
ACT_JUMP_SOUTH = "JUMP_SOUTH"
ACT_JUMP_WEST = "JUMP_WEST"

ACT_BUILD_WALL_NORTH = "BUILD_NORTH"
ACT_BUILD_WALL_EAST = "BUILD_EAST"
ACT_BUILD_WALL_SOUTH = "BUILD_SOUTH"
ACT_BUILD_WALL_WEST = "BUILD_WEST"

ACT_REMOVE_WALL_NORTH = "REMOVE_NORTH"
ACT_REMOVE_WALL_EAST = "REMOVE_EAST"
ACT_REMOVE_WALL_SOUTH = "REMOVE_SOUTH"
ACT_REMOVE_WALL_WEST = "REMOVE_WEST"

ACT_TRANSFORM = "TRANSFORM"

ACT_TRANSFER_NORTH = "TRANSFER_NORTH"
ACT_TRANSFER_EAST = "TRANSFER_EAST"
ACT_TRANSFER_SOUTH = "TRANSFER_SOUTH"
ACT_TRANSFER_WEST = "TRANSFER_WEST"
